apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-service-config
  namespace: employee-mgmt
data:
  EUREKA_URI: "http://eureka-server:8761/eureka"
  # Swap to Postgres in production (see terraform/localstack + RDS notes in SETUP.md)
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:employeedb"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_DRIVER: "org.h2.Driver"
  SPRING_JPA_DIALECT: "org.hibernate.dialect.H2Dialect"
