apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-mgmt
  labels:
    app: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
