apiVersion: v1
kind: ConfigMap
metadata:
  name: department-service-config
  namespace: employee-mgmt
data:
  EUREKA_URI: "http://eureka-server:8761/eureka"
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:departmentdb"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_DRIVER: "org.h2.Driver"
  SPRING_JPA_DIALECT: "org.hibernate.dialect.H2Dialect"
