apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: employee-mgmt
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: <ECR_REGISTRY>/employee-mgmt/eureka-server:<IMAGE_TAG>
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 15
