apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eureka-server
  namespace: employee-mgmt
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eureka-server
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
